import { Venue } from '../types/venue';
import { ShyTextPost } from '../types/shytext';

export const DEMO_VENUES: Venue[] = [
  {
    id: 'demo-paddys-corner',
    provider: 'demo',
    providerPlaceId: 'demo-paddys-corner',
    name: "Paddy's Corner",
    address: '5 Rue Example',
    category: 'Bar',
    latitude: 48.853,
    longitude: 2.35,
    activeCount: 3,
  },
  {
    id: 'demo-campus-library',
    provider: 'demo',
    providerPlaceId: 'demo-campus-library',
    name: 'Campus Library',
    address: 'University Quad',
    category: 'Study',
    latitude: 48.854,
    longitude: 2.351,
    activeCount: 1,
  },
  {
    id: 'demo-central-park',
    provider: 'demo',
    providerPlaceId: 'demo-central-park',
    name: 'Riverside Park',
    address: 'River Walk',
    category: 'Park',
    latitude: 48.852,
    longitude: 2.349,
    activeCount: 0,
  },
];

export function seedShyTexts(venueId: string): ShyTextPost[] {
  const now = Date.now();
  return [
    {
      id: 'seed-sarah',
      userId: 'seed-sarah',
      authorId: 'seed-sarah',
      authorName: 'Sarah',
      authorAge: 22,
      venueId,
      intent: 'coffee',
      category: 'coffee',
      message: 'Waiting for a friend, happy to chat.',
      createdAt: now - 12 * 60000,
      expiresAt: now + 18 * 60000,
      status: 'active',
      visibilityMode: 'open',
      responseCount: 0,
    },
    {
      id: 'seed-adam',
      userId: 'seed-adam',
      authorId: 'seed-adam',
      authorName: 'Adam',
      authorAge: 24,
      venueId,
      intent: 'play',
      category: 'play',
      message: 'Anyone down for pool?',
      createdAt: now - 5 * 60000,
      expiresAt: now + 25 * 60000,
      status: 'active',
      visibilityMode: 'open',
      responseCount: 0,
    },
    {
      id: 'seed-marie',
      userId: 'seed-marie',
      authorId: 'seed-marie',
      authorName: 'Marie',
      authorAge: 21,
      venueId,
      intent: 'chat',
      category: 'chat',
      message: 'New in Lyon 👋',
      createdAt: now - 18 * 60000,
      expiresAt: now + 12 * 60000,
      status: 'active',
      visibilityMode: 'open',
      responseCount: 0,
    },
  ];
}
